---
title: "Graphing"
author: "Fiona Adams"
date: "2/14/2020"
output: html_document
---

```{r}
library(quanteda)
```

```{r}
mapped_data <- read.csv("mapped_data.csv")
transcripts <- readtext("All_Transcripts/*.docx")
```

Make quantile graph:

```{r}
#make column with number of sentences in a document
transcripts <- transcripts %>% mutate(nchar = nsentence(text))

#find out the number of sentences in each quantile (25%, 50%, and 75%)
for(i in 1:nrow(transcripts)){
  nchars = transcripts$nchar[i]
  transcripts$quantile1[i] <- quantile(1:nchars)[2] #25%
  transcripts$quantile2[i] <- quantile(1:nchars)[3] #50%
  transcripts$quantile3[i] <- quantile(1:nchars)[4] #75% 
}

#get rid of .docx so that we can more easily leftjoin with mapped cluster data
for(i in 1:nrow(transcripts)){
  transcripts[1][i,] <- str_remove(transcripts[1][i,], ".docx")
}

#get rid of text column, we don't need that once we left join!
transcripts_filt <- transcripts %>% select(doc_id, quantile1, quantile2, quantile3)
```

Left join transcripts to new, and then make a column that determines whether a sentence is between two quantiles or not.

```{r}
quantile_with_mappeddta <- left_join(mapped_data, transcripts_filt, by="doc_id")
```

```{r}
#case_when to determine which quantile sentence_id is within

sentence_quantiles <- quantile_with_mappeddta %>%
  mutate(
    quantile = case_when(
      sentence_id <= quantile1 ~ "1", #less than 25%
      sentence_id <= quantile2 & sentence_id > quantile1 ~ "2", #between 25 and 50%
      sentence_id <= quantile3 & sentence_id > quantile2 ~ "3", #between 50 and 75%
      sentence_id > quantile3 ~ "4", #between 75 and 100%
    )
  )
```

```{r}
# library(tidyr)
# long_new <- sentence_quantiles %>% 
#   select(-clusters) %>% 
#   pivot_longer(., cols = starts_with("cluster"), names_to="cluster") %>% 
#   filter(!is.na(value))
```

```{r}
#this gives us:
# of all of the sentences in topic 1, where are they?

cluster_quantile_total <- sentence_quantiles %>%
  group_by(results, quantile) %>% 
  tally() %>%
  rename(clust_quant=n)

cluster_total <- sentence_quantiles %>%
  group_by(results) %>%
  tally() %>%
  rename(clust = n)

quantile_probs <- left_join(cluster_quantile_total, cluster_total, by="results")

#p = probability of a topic (cluster) being in a given quantile
quantile_probs <- quantile_probs %>% mutate(p = clust_quant/clust)
```

```{r}
# how many sentences in topic i are in quartile i / total # of sentences in quartile 1
# of all the sentences in quartile 1, what fraction belong in topic 1, 2, 3, ..20 

cluster_quantile_total <- sentence_quantiles %>%
  group_by(results, quantile) %>% 
  tally() %>%
  rename(clust_quant=n)

#how many sentences are in each quantile?
quantile_total <- sentence_quantiles %>%
  group_by(quantile) %>%
  tally()

quantile_probs <- left_join(cluster_quantile_total, quantile_total, by="quantile")

#p = probability of a topic (cluster) being in a given quantile
quantile_probs <- quantile_probs %>% mutate(p = clust_quant/n)
```


```{r}
library(ggplot2)

#what do we want?
#Pull out the "meaningful" clusters and only display those
quantile_probs %>% 
  ggplot(aes(x=quantile, y=p)) + 
  geom_col(aes(fill=factor(results))) + 
  facet_grid(~results) +
  ggtitle("Probability of each sentence being in a given topic, by quantile: \n Average over all interviews")
```

```{r}
# how many sentences in topic i are in quartile i / total # of sentences in quartile 1
# of all the sentences in quartile 1, what fraction belong in topic 1, 2, 3, ..20 

cluster_quantile_greg <- sentence_quantiles %>%
  filter(doc_id=="Anderson_Greg") %>%
  group_by(results, quantile) %>% 
  tally() %>%
  rename(clust_quant=n)

#how many sentences are in each quantile?
quantile_total <- sentence_quantiles %>%
  group_by(quantile) %>%
  tally()

quantile_probs <- left_join(cluster_quantile_greg, quantile_total, by="quantile")

#p = probability of a topic (cluster) being in a given quantile
quantile_probs <- quantile_probs %>% mutate(p = clust_quant/n)

quantile_probs %>% 
  ggplot(aes(x=quantile, y=p)) + 
  geom_col(aes(fill=factor(results))) + 
  facet_grid(~results) +
  ggtitle("Probability of each sentence being in a given topic, by quantile: \n Greg Anderson's Interview")
```

