---
title: "Graphing"
author: "Fiona Adams"
date: "2/14/2020"
output: html_document
---

```{r}
library(quanteda)
```

```{r}
mapped_data <- read.csv("mapped_data.csv")
transcripts <- readtext("All_Transcripts/*.docx")
```

Make quantile graph:

```{r}
#make column with number of sentences in a document
transcripts <- transcripts %>% mutate(nchar = nsentence(text))

#find out the number of sentences in each quantile (25%, 50%, and 75%)
for(i in 1:nrow(transcripts)){
  nchars = transcripts$nchar[i]
  transcripts$quantile1[i] <- quantile(1:nchars)[2]
  transcripts$quantile2[i] <- quantile(1:nchars)[3]
  transcripts$quantile3[i] <- quantile(1:nchars)[4]
}

#get rid of .docx so that we can more easily leftjoin with mapped cluster data
for(i in 1:nrow(transcripts)){
  transcripts[1][i,] <- str_remove(transcripts[1][i,], ".docx")
}

#get rid of text column, we don't need that once we left join!
transcripts_filt <- transcripts %>% select(doc_id, quantile1, quantile2, quantile3)
```

Left join transcripts to new, and then make a column that determines whether a sentence is between two quantiles or not.

```{r}
quantile_with_mappeddta <- left_join(mapped_data, transcripts_filt, by="doc_id")
```

```{r}
#case_when to determine which quantile sentence_id is within

testing123 <- quantile_with_mappeddta %>%
  select(sentence_id:description, clusters, quantile1, quantile2, quantile3) %>%
  mutate(
    sent_quantile = case_when(
      sentence_id <= quantile1 ~ "quantile1",
      sentence_id <= quantile2 ~ "quantile2",
      sentence_id <= quantile3 ~ "quantile3",
      sentence_id > quantile3 ~ "quantile4",
    )
  ) %>%
  select(doc_id, sentence_id, sent_quantile)
```

Alternative way to do this:
```{r}
library(tidyr)
vars <- c("sentence_id", paste0("cluster_", 1:20))
#work on this! make long for better EDA stuffs
long_new <- pivot_longer(new, cols = starts_with("cluster"), names_to="cluster")

median <- median(long_new$sentence_id)

# 0 --> 164: First section
# 164 --> 328: Second section
# 328 --> 656: Third section
# 656 --> 984: Fourth section
# 984 --> 1297: Fifth section
long_new <- long_new %>%
  filter(!is.na(value)) %>%
  select(id, sentence_id, doc_id, description, family_experience, treatment_prof, personal_experience, value) %>%
  mutate(quadrant = ifelse(sentence_id<=median/2, "Quadrant 1", ifelse(sentence_id <=median, "Quadrant 2", ifelse(sentence_id <= median*2, "Quadrant 3", ifelse(sentence_id <= median*3, "Quadrant 4", "Quadrant 5"))))) #case_when would be better here! create 4 new var: quad 1, quad 2, etc.
```

```{r}
#Made deciles but they're not dependent on the length of an individual interview
library(ggplot2)
long_new %>% 
  filter(id==3) %>%
  ggplot(aes(x=quadrant, y=value)) + geom_jitter()
```
