---
title: 'Semester1Progress: Topic Modeling Ethnographic Interviews'
author: "Fiona Adams"
date: "1/3/2020"
output:
  pdf_document: default
  html_document: default
header-includes: \usepackage{graphicx}
---

## Introduction

This will be heavily dependent on the final product! 

Some useful lit so far:
• https://www.researchgate.net/publication/299552252_Statistical_Topic_Modeling_for_News_Articles
• https://arxiv.org/pdf/1808.01175.pdf
• https://towardsdatascience.com/thats-mental-using-lda-topic-modeling-to-investigate-the-discourse-on-mental-health-over-time-11da252259c3
• https://towardsdatascience.com/light-on-math-machine-learning-intuitive-guide-to-latent-dirichlet-allocation-437c81220158
• http://www.jmlr.org/papers/volume3/blei03a/blei03a.pdf

## Dataset

This dataset is from the Minnesota Opioid Project, a collection of 50 ethnographic interviews conducted by Amy Sullivan. The interviewees are all Minnesotans influenced by the opioid epidemic. They include treatment professionals, people who previously had Opioid Use Disorder (OUD), and people who have seen a family member die from opioid overdose. Each interview has about 10,000 to 15,000 words, meaning topic modelling is a potential time-saver.

## Goal

Make ethnographic interview analysis easier! Not unsupervised necessarily, but not *mind-numbingly tedious* as Amy describes it.

## Tried

**Noun/verb phrases:**

• Split on sentence level
• Get key noun/verb phrases for each sentence and make a new dataset with these phrases
• Cluster noun/verb phrases together based on string distance

Result: unintelligible clusters, heavy overlap

**Document comparison:**

• Cosine similarity & Euclidean distance between documents
• http://text2vec.org/similarity.html

Result: great for comparing and determining whether documents are similar, validating the usefulness of topic modeling. But, not useflu for final product.

**More noun/verb phrase:**

• Using same approach as final (split on paragraph level, same cleaning), take the top # (played around with this #, settled on 500 for computation reasons) noun/verb phrases from the corpus
• Filter paragaphs so that each paragraph is consisted of just its top noun/verb phrases
• Perform LDA on these newly filtered paragarphs

Result: clearly labelable clusters, but clusters didn't give unique results, so not very useful for historians

**Different dataset**

• Repeated the above and final approach on a general dataset of Wikipedia articles, in line with methodology from https://arxiv.org/pdf/1808.01175.pdf. 
• Hope was to compare clusters and see if it was easier to label given clusters from another dataset
• Super long computation time, as expected

Result: Not useful--but may be worth approaching again

## In final approach

See CleaningandLDA.Rmd for the work for the below.

Cleaning:

• Split each interview into its respective paragraphs
• Treat each paragraph as a separate "document" but label the paragraphs based on the document they originally came from (ex. doc 9--can be mapped to doc 9 in the original dataset) 
• Remove paragraphs with <20 characters, meaning most of the questions Amy asks in the interview are filtered out, and any "yes," "no," etc. answers are gone as well
• Take out stop words ex. "it," "be," etc. using stopwords()

Modelling:

• Latent Dirichlet Allocation (LDA)
• Assume the paragraphs have 10 topics

## Next Steps

**Will be in final:**

*Almost there:*
• Find and concatenate words that had relatively high probabilities of being together--these words are found, but need to be concatenated. See CoOccuringWords.Rmd--so close, yet so far!! Need some guidance on the very last part. Working with Leslie on this.
• Then, re-run LDA

*To do:*
• Manually label each cluster based on its themes
• Map the words from each cluster back to sentences in each document

**Attempt along the way:**

*Cleaning:*

• Decided against stemming and lemmatization due to some loss of meaning, revisit using different methods
• Also revisit CountVectorizer. See https://www.rdocumentation.org/packages/superml/versions/0.4.0/topics/CountVectorizer

*LDA Adjustments:*

• Re-run LDA where each "document" is a smaller phrase rather than a full paragraph

*Try other clustering methods:*

• See https://www.sciencedirect.com/science/article/pii/S0020025518308028 for comparison of methods--LDA has some big limitations!
• See if achieve better clusters using *Nonnegative Matrix Factorization*. See https://towardsdatascience.com/topic-modeling-for-the-new-york-times-news-dataset-1f643e15caac
• See if achieve better clusters using *Stochastic Block Model*. See https://advances.sciencemag.org/content/4/7/eaaq1360
• Determine whether worthwhile to attempt a *doc2vec* approach, using Python (a language I'm less familiar with). See https://arxiv.org/pdf/1808.01175.pdf and https://towardsdatascience.com/using-word2vec-to-analyze-news-headlines-and-predict-article-success-cdeda5f14751 and https://cs.stanford.edu/~quocle/paragraph_vector.pdf

*Labeling the clusters:*

• Work on "auto-labelling" clusters using different dataset to train, ex. addiction medicine handbooks, or Wikipedia articles specifically about substance abuse

## Dataset: Description of Each Person Interviewed

\begin{table}[]
\resizebox{\textwidth}{!}{%
\begin{tabular}{ll}
Mark Willenbring & Doctor at NIH \\
Verne Wagner & Father of son addicted to meth, started NarAnon group \\
Andrew Tuttle & Psychiatrist, became addicted to opioids \\
Lorraine Teel & Started program for people addicted primarily to opioids \\
Kathie Simon Frank & Mother of daughter addicted to opioids \\
Yussuf Shafie & CEO and the director of Alliance Wellness Center. \\
Marvin Seppala & Once addicted to amphetamines \\
Star Selleck & Father of son addicted to various substances \\
Shelley Roberts Gyllen & Sister to brother who died from narcotic overdose \\
Charles Reznioff & Doctor focused on addiction medicine \\
Sue Purchase & Harm reduction specialist \\
Kim Powers & Mother of daughter addicted to opioids \\
Cody Petrich & Son of mother addicted to opioids \\
Ann Perry & Mother of son addicted to opioids \\
Margarita Ortega & Ex-opioid user \\
Michael O'Neill & Ex-cocaine user and father of son addicted to opioids \\
Richard Moldenhauer & Worked at various drug treatment centers \\
Kirsten Milun & Mother of son addicted to opioids \\
Ian McLoone & Ex-opioid user and son of mother addicted to opioids \\
Rose McKinney & Mother of child addicted to opioids \\
Mary McCarthy & Harm reduction professional \\
Lori Lewis & Mother of son addicted to opioids \\
Robert Levy & Addiction medicine doctor \\
Wade Lang & Ex-opioid user \\
Maris Krause & Ex-opioid user \\
Chandra Kelvie & Daughter of parents who used opioids \\
Maggie Kazel NO TRANSCRIPT & Harm reduction professional \\
Jeff Kazel & Law enforcement professional \\
Dean Johnson & Father of son addicted to opioids \\
Chris Johnson & Addiction medicine doctor \\
Julie Hooker & Treatment professional \\
Janise Holter & Mother of child addicted to opioids \\
Deb Holman & Treatment professional \\
Chuck Hilger & Ex-opioid user and treatment professional \\
Carson Gardner & Mother of child addicted to opioids, researcher \\
Frank Eden Rae & Treatment professional focused on harm reduction \\
Carol Folkowski & Treatment professional \\
Adam Fairbanks & Treatment professional focused on harm reduction \\
Robin Evanson & Ex-opioid user \\
Nancy Espuche & Mother of child addicted to opiods \\
Gloria Englund & Mother of son addicted to opioids \\
Stephanie Devich & Treatment professional \\
Paula DeSanto & Treatment professional \\
Jamison Danielson & Treatment professional focused on harm reduction \\
Brandon Coleman & Son of mother addicted to opioids and ex-opioid user \\
Bill Cole & Father of child addicted to opioids \\
Emily Brunner & Addiction medicine doctor \\
Janie Bining Colford & Mother of child addicted to opioids \\
Linda Berry-Brede & Mother of child addicted to opioids \\
Thilo Beck & Addiction medicine doctor \\
Greg Anderson & Social worker
\end{tabular}%
}
\end{table}

